# ----------------------------------------------------------------------------
# Customize Options: Must Change
#
# Title:
title: ğŸ…€ğŸ…„ğŸ„°ğŸ…ğŸ„°ğŸ„½ğŸ…ƒğŸ„¸ğŸ„½ğŸ„´ ğŸ„²ğŸ…ğŸ„´ğŸ„°ğŸ…ƒğŸ„¸ğŸ……ğŸ„¸ğŸ…ƒğŸ…ˆ
tagline: "Create and share at a distance"
description: "Create and share at a distance"

url: "https://quarantine-creativity.com/"

# Set default og:image
# From Unsplash: https://unsplash.com/photos/1_CMoFsPfso
defaults:
  -
    scope:
      path: ""
    values:
      image: ""

# ----------------------------------------------------------------------------
# Customize Options: Optional
#
# See: https://material.io/guidelines/style/color.html
# Use color-name-value, like pink-200 or deep-purple-100
# brand_color: "green-400"

# How article URLs are structured.
# See: https://jekyllrb.com/docs/permalinks/
permalink: posts/:title/

# Language. For example, if you write in Japanese, use "ja"
lang: "en"

# How many posts are visible on the home page without clicking "View More"
num_posts_visible_initially: 5

# Date format: See http://strftime.net/
date_format: "%b %-d, %Y"
# ----------------------------------------------------------------------------

include:
  - /assets/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - mix-manifest.json
  - webpack.mix.js
  - package-lock.json
  - package.json
  - hot
  - LICENSE.txt
  - README.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-readme-index
